version: "3.9"
services:
  db:
    image: postgres:15.1-alpine3.17
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: yadokari
    restart: always
  backend:
    depends_on:
      - db
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TDFK: ${TDFK}
      VERIFICATION_TOKEN: ${VERIFICATION_TOKEN}
      BOT_USER_OAUTH_TOKEN: ${BOT_USER_OAUTH_TOKEN}
      BOT_USER: ${BOT_USER}
volumes:
  data:
